### ISSUE TITLE
No plugin called YPTStorage Plugin

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube-Storage#1]
> Enable YPTStorage Plugin
> Make sure you enable it before your installation, this is necessary because the Storage installation will check your plugin during the configuration assistant
> 
> If you do not have the plugin yet, get it here

I don't see any plugin called like this , not on the web you linked or anywhere . Do I need to git pull or something ?

**Comment by DanielnetoDotCom** [comment]
Hi, 

thanks for folowing it.

the YPTStorage is a paid plugin and I just add it on the Plugins store.

also, it is on the demo site. I will update the README soon

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Thanks for the reply , but in my opinion it's too expensive . And the videoHLS also . I just don't get what the plugin does exactly . I though the videoHLS were just a command line on the ffmpeg that I have been using until now . Example : 
 ffmpeg -i {$pathFileName} -profile:v baseline -level 4.2 -s 1920x1080 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls index.m3u8 {$destinationFile}

**Comment by jaynelim** [comment]
yes you're pricing the plugins at too much price. makes the open source project difficult to use. i know u need to be compensated for your time, but pricing plugins at $60 each is just too much.

**Comment by akhilleusuggo** [comment]
The idea behind an open-source it to be free , but there's no doubt that they need to make some profit from this amazing work . If they place plugins at that hgiher prices , none gonna buy them ( maye 2 or 3 ) , but with a normal prices I think everybody will be interested on them and the final benefit will be higher . 
Just to mention that YouPHPTube has doubled the price of ALL the plugins . I remember seen this project 2 years ago at the start , I wasn't interested but took a look , and the prices I remember very well they were 50% less than they are today . The resolution switch were for 9.99$ now 20$ ......

For 60$ storage plugin I'll

**Comment by EnrOn-tv** [comment]
comcordo pq para eu comora aqui no brasil sai muito carro se tivese mais em conta teria comprado todos ja
