### ISSUE TITLE
SecureVideosDirectory

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube-Storage#4]
in the apache2 error log, the following information is displayed with each access:
`{" authorization ": true," msg ":" SecureVideosDirectory NOT enabled "}`
I suspect it refers to the same plugin.
The storage works normally it is only the hint.
What does that mean?

greeting
Donnerstein

**Comment by DanielnetoDotCom** [comment]
Yes, you are right.

If you have the SecureVideosDirectory enabled you will have a token to access the files.

so the file will not be available if you direct access to it.

**Comment by Donnerstein** [comment]
What's the use of this plugin?
Why should one prevent the direct access to the file?

**Comment by DanielnetoDotCom** [comment]
Hi

some times I can grab your video link directly from your source and share it on my site.
so you will host the video and will consume your bandwidth.

I am not talking about embed code, I am talking about a link directly to your mp4 file

with this plugin it will require a token that expires after some time, so if I copy your MP4 link file it will be useless after the token expires.

**Comment by Donnerstein** [comment]
I understand, thanks.
